<?php

return [
    [
        'icon' => 'halal-reg',
        'slug' => 'sertifikat-halal-reguler',
        'title' => 'Sertifikat Halal Reguler',
        'desc' => 'Pendampingan sertifikasi halal jalur reguler bagi usaha atau produk yang berdasarkan pemeriksaan awal tidak memenuhi kriteria Self-Declare dan memerlukan pemeriksaan oleh LPH.',
        'detail' => 'Pendampingan Sertifikat Halal Reguler untuk usaha atau produk yang tidak memenuhi kriteria Self-Declare. Ruang lingkup meliputi pemetaan produk dan fasilitas, penyiapan Penyelia Halal serta dokumen Sistem Jaminan Produk Halal (SJPH), pengajuan melalui SIHALAL, pemilihan Lembaga Pemeriksa Halal (LPH), pendampingan pemeriksaan atau audit dan pengujian bila diperlukan, pemenuhan catatan, penetapan kehalalan, hingga penerbitan sertifikat elektronik oleh BPJPH.',
        'benefits' => [
            'Pemetaan jalur reguler berdasarkan karakteristik produk, bahan, dan proses produksi.',
            'Pendampingan dokumen SJPH, Penyelia Halal, fasilitas, bahan, dan proses produk halal.',
            'Koordinasi administratif selama pemeriksaan LPH dan pemenuhan catatan pemeriksaan.',
            'Pemantauan proses penetapan halal sampai sertifikat diterbitkan BPJPH.',
        ],
        'suitable_for' => 'Pelaku usaha yang produknya tidak memenuhi kriteria Self-Declare, menggunakan bahan atau proses yang memerlukan penelusuran lebih lanjut, memiliki proses produksi kompleks, atau berdasarkan ketentuan wajib melalui pemeriksaan LPH.',
        'workflow_steps' => [
            'Konsultasi dan penetapan jalur sertifikasi berdasarkan produk, bahan, proses, serta skala usaha',
            'Penyiapan legalitas usaha, data produk, bahan, fasilitas, Penyelia Halal, dan dokumen SJPH',
            'Pengajuan permohonan sertifikasi halal reguler melalui SIHALAL',
            'Pemeriksaan kelengkapan permohonan dan pemilihan Lembaga Pemeriksa Halal (LPH)',
            'Pemeriksaan dokumen dan fasilitas oleh LPH serta pengujian laboratorium apabila diperlukan',
            'Pemenuhan tindakan perbaikan atau dokumen tambahan berdasarkan hasil pemeriksaan',
            'Penyampaian hasil pemeriksaan untuk proses penetapan kehalalan produk',
            'Penerbitan sertifikat halal elektronik oleh BPJPH dan arahan tindak lanjut',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi Sertifikat Halal Reguler. Mohon dibantu pemeriksaan jalur, kebutuhan SJPH, dokumen, dan tahapan pemeriksaan LPH.',
    ],
    [
        'icon' => 'nib',
        'slug' => 'nib-nomor-induk-berusaha',
        'title' => 'NIB — Nomor Induk Berusaha',
        'desc' => 'Pendampingan penerbitan NIB melalui OSS berbasis risiko, termasuk pemilihan KBLI dan identifikasi perizinan lanjutan sesuai tingkat risiko kegiatan usaha.',
        'detail' => 'Pendampingan penerbitan Nomor Induk Berusaha (NIB) melalui sistem OSS sebagai identitas resmi pelaku usaha. Proses mencakup pemeriksaan bentuk pelaku usaha, pemilihan KBLI, pengisian data usaha dan proyek, validasi persyaratan dasar, serta identifikasi tingkat risiko. NIB tidak selalu menjadi satu-satunya izin; kegiatan berisiko menengah atau tinggi dapat memerlukan Sertifikat Standar, izin, dan/atau PB-UMKU sesuai sektor.',
        'benefits' => [
            'Pemilihan KBLI dan ruang lingkup kegiatan usaha yang lebih terarah.',
            'Pendampingan pengisian data pelaku usaha, lokasi, modal, dan kegiatan usaha di OSS.',
            'Identifikasi tingkat risiko serta kewajiban izin lanjutan yang ditampilkan OSS.',
            'Pemeriksaan dokumen NIB dan daftar kewajiban setelah penerbitan.',
        ],
        'suitable_for' => 'Pelaku usaha perorangan, badan usaha, atau badan hukum yang akan memulai kegiatan usaha, menambah kegiatan atau lokasi, maupun menertibkan identitas dan perizinan berusaha melalui OSS.',
        'workflow_steps' => [
            'Identifikasi bentuk pelaku usaha, bidang kegiatan, lokasi, dan tujuan pengurusan',
            'Penentuan KBLI serta pemeriksaan awal tingkat risiko dan persyaratan sektor',
            'Penyiapan identitas, dokumen badan usaha, kontak, lokasi, modal, dan data kegiatan usaha',
            'Pembuatan atau aktivasi hak akses OSS dan pengisian data pelaku usaha',
            'Pengisian data usaha atau proyek serta validasi persyaratan dasar yang berlaku',
            'Konfirmasi pernyataan mandiri dan penerbitan NIB oleh sistem OSS',
            'Pemeriksaan Sertifikat Standar, izin, atau PB-UMKU lanjutan sesuai hasil pemetaan risiko',
            'Penyerahan dokumen dan arahan pemenuhan kewajiban perizinan setelah NIB terbit',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin mengurus NIB melalui OSS. Mohon dibantu pemilihan KBLI, persiapan data usaha, dan pemeriksaan izin lanjutan sesuai tingkat risiko.',
    ],
    [
        'icon' => 'akta',
        'slug' => 'akta-pendirian-badan-usaha',
        'title' => 'Akta Pendirian Badan Usaha',
        'desc' => 'Pendampingan penentuan bentuk usaha dan proses pendirian PT, CV, atau Firma melalui notaris dan sistem AHU sesuai karakter serta kebutuhan usaha.',
        'detail' => 'Pendampingan pendirian usaha dimulai dengan memilih bentuk yang sesuai berdasarkan jumlah pendiri, tanggung jawab, struktur modal, dan kebutuhan operasional. PT persekutuan modal didirikan dengan akta notaris dan memperoleh pengesahan badan hukum melalui SABH, sedangkan CV dan Firma didaftarkan oleh notaris melalui SABU sebagai badan usaha non-badan hukum. Perseroan Perorangan untuk kriteria UMK menggunakan pernyataan pendirian elektronik dan tidak memakai akta notaris.',
        'benefits' => [
            'Penjelasan perbedaan status, tanggung jawab, dan struktur PT, Perseroan Perorangan, CV, serta Firma.',
            'Pendampingan penyiapan data pendiri, pengurus, modal, kegiatan usaha, dan pemilik manfaat.',
            'Koordinasi penyusunan akta dan pengajuan melalui notaris untuk bentuk usaha yang mensyaratkannya.',
            'Pemeriksaan hasil pengesahan atau pendaftaran AHU dan kebutuhan legalitas lanjutan.',
        ],
        'suitable_for' => 'Calon pelaku usaha yang membutuhkan struktur usaha resmi, pendiri yang akan membentuk PT, CV, atau Firma, serta pelaku UMK yang perlu menilai kesesuaian Perseroan Perorangan.',
        'workflow_steps' => [
            'Konsultasi bentuk usaha berdasarkan pendiri, tanggung jawab, modal, dan rencana kegiatan',
            'Penyiapan identitas pendiri, pengurus, pemegang saham atau sekutu, alamat, modal, dan KBLI',
            'Pemeriksaan dan pemesanan nama usaha sesuai bentuk yang dipilih',
            'Penyusunan serta persetujuan konsep akta oleh notaris, atau pernyataan elektronik untuk Perseroan Perorangan',
            'Penandatanganan dokumen dan pemenuhan pembayaran PNBP yang berlaku',
            'Pengajuan pengesahan PT melalui SABH atau pendaftaran CV dan Firma melalui SABU',
            'Penerbitan akta dan SK pengesahan atau Surat Keterangan Terdaftar dari AHU',
            'Arahan tindak lanjut NIB, NPWP, pemilik manfaat, dan perizinan sektoral yang diperlukan',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi pendirian usaha. Mohon dibantu menentukan bentuk PT, Perseroan Perorangan, CV, atau Firma serta dokumen dan proses AHU yang sesuai.',
    ],
    [
        'icon' => 'pajak',
        'slug' => 'npwp-dan-pelaporan-pajak',
        'title' => 'NPWP dan Pelaporan Pajak',
        'desc' => 'Pendampingan registrasi atau aktivasi administrasi perpajakan serta penyusunan dan pelaporan SPT melalui Coretax berdasarkan data dan kewajiban wajib pajak.',
        'detail' => 'Pendampingan administrasi NPWP dan pelaporan pajak melalui Coretax DJP untuk wajib pajak orang pribadi maupun badan. Ruang lingkup disesuaikan dengan status dan kewajiban wajib pajak, meliputi registrasi atau aktivasi akun, permintaan Kode Otorisasi atau Sertifikat Digital, pemeriksaan profil, penyiapan dokumen keuangan dan bukti potong, penyusunan konsep SPT, peninjauan bersama wajib pajak, pengiriman, serta pengarsipan Bukti Penerimaan Elektronik. Nilai dan kebenaran data tetap harus dikonfirmasi oleh wajib pajak.',
        'benefits' => [
            'Pemetaan administrasi dan kewajiban pajak berdasarkan profil wajib pajak.',
            'Pendampingan aktivasi Coretax dan Kode Otorisasi atau Sertifikat Digital.',
            'Pemeriksaan kelengkapan dokumen pendukung sebelum penyusunan SPT.',
            'Pengarsipan bukti lapor serta identifikasi tindak lanjut pembayaran atau pembetulan.',
        ],
        'suitable_for' => 'Orang pribadi atau badan usaha yang perlu mendaftar atau mengaktifkan administrasi perpajakan, menyiapkan akses Coretax, dan melaporkan SPT berdasarkan catatan serta dokumen transaksi yang tersedia.',
        'workflow_steps' => [
            'Identifikasi status wajib pajak, jenis usaha, masa atau tahun pajak, dan kewajiban pelaporan',
            'Penyiapan identitas, NPWP atau NIK, dokumen badan, data kontak, dan dokumen pendukung',
            'Registrasi atau aktivasi akun Coretax serta pembaruan profil bila diperlukan',
            'Permintaan Kode Otorisasi atau Sertifikat Digital untuk penandatanganan elektronik',
            'Pengumpulan dan rekonsiliasi laporan keuangan, bukti potong, pembayaran, dan data transaksi',
            'Penyusunan konsep SPT induk dan lampiran sesuai profil serta data wajib pajak',
            'Peninjauan dan persetujuan isi SPT oleh wajib pajak sebelum pengiriman',
            'Pengiriman SPT, penyimpanan Bukti Penerimaan Elektronik, dan arahan tindak lanjut',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi NPWP dan pelaporan pajak melalui Coretax. Mohon dibantu memetakan dokumen, aktivasi akun, dan kewajiban pelaporan saya.',
    ],
    [
        'icon' => 'bpom',
        'slug' => 'bpom',
        'title' => 'BPOM',
        'desc' => 'Pendampingan klasifikasi dan registrasi izin edar atau PB-UMKU BPOM, terutama untuk pangan olahan dalam kemasan eceran yang wajib didaftarkan.',
        'detail' => 'Pendampingan registrasi produk BPOM diawali dengan klasifikasi untuk menentukan apakah produk memerlukan izin edar BPOM, izin lain seperti SPP-IRT, atau termasuk pengecualian. Untuk pangan olahan yang wajib didaftarkan, proses dapat mencakup penyiapan NIB dan KBLI, akun perusahaan pada OSS dan e-Reg RBA, pemenuhan dokumen sarana produksi, data komposisi dan proses, hasil uji bila dipersyaratkan, rancangan label, pembayaran PNBP, serta pemenuhan hasil evaluasi sampai PB-UMKU atau nomor izin edar diterbitkan. Persyaratan berbeda menurut kategori dan karakter produk.',
        'benefits' => [
            'Pemeriksaan awal jalur perizinan berdasarkan kategori, proses, kemasan, dan cara distribusi produk.',
            'Pendampingan data perusahaan, sarana produksi, komposisi, proses, mutu, dan rancangan label.',
            'Pendampingan pengajuan serta pemenuhan pertanyaan atau catatan evaluasi BPOM.',
            'Pemeriksaan dokumen persetujuan dan kewajiban setelah izin edar diterbitkan.',
        ],
        'suitable_for' => 'Produsen atau importir pangan olahan dalam kemasan eceran yang berdasarkan klasifikasi wajib memiliki PB-UMKU atau izin edar BPOM, termasuk usaha yang perlu memastikan apakah produknya masuk jalur BPOM atau perizinan lain.',
        'workflow_steps' => [
            'Klasifikasi produk dan penentuan jalur BPOM, SPP-IRT, atau pengecualian yang sesuai',
            'Pemeriksaan NIB, KBLI, legalitas perusahaan, peran produsen atau importir, dan sarana produksi',
            'Pembuatan atau sinkronisasi akun OSS dan akun perusahaan pada sistem e-Reg RBA BPOM',
            'Penyiapan dokumen sarana serta pemenuhan pemeriksaan atau rekomendasi fasilitas bila dipersyaratkan',
            'Penyusunan data produk: komposisi, proses, spesifikasi, masa simpan, hasil uji, klaim, dan rancangan label',
            'Pengajuan registrasi produk dan pembayaran PNBP sesuai surat perintah bayar',
            'Pemantauan evaluasi serta pemenuhan tambahan data atau perbaikan dari evaluator BPOM',
            'Penerbitan PB-UMKU atau nomor izin edar dan arahan kewajiban pascapersetujuan',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi izin edar BPOM. Mohon dibantu klasifikasi produk, pemeriksaan jalur perizinan, dokumen perusahaan, produk, dan label.',
    ],
    [
        'icon' => 'haki',
        'slug' => 'haki',
        'title' => 'HAKI',
        'desc' => 'Pendampingan permohonan Kekayaan Intelektual—terutama merek, pencatatan hak cipta, dan desain industri—sesuai jenis objek dan prosedur DJKI.',
        'detail' => 'Pendampingan Kekayaan Intelektual (KI) dimulai dengan menentukan jenis pelindungan yang tepat, terutama pendaftaran merek, pencatatan hak cipta, atau pendaftaran desain industri. Setiap jenis memiliki persyaratan dan proses pemeriksaan berbeda. Pendampingan dapat mencakup penelusuran awal, klasifikasi barang atau jasa untuk merek, penyiapan identitas dan dokumen objek, pengajuan elektronik, pembayaran PNBP, pemantauan formalitas, pengumuman atau pemeriksaan substantif bila berlaku, serta respons administratif. Penelusuran awal tidak menjamin permohonan pasti diterima karena keputusan berada pada DJKI.',
        'benefits' => [
            'Identifikasi jenis pelindungan KI yang sesuai dengan merek, karya, atau desain.',
            'Penelusuran awal dan pemeriksaan elemen yang berpotensi menimbulkan kendala.',
            'Pendampingan klasifikasi serta penyiapan dokumen permohonan elektronik.',
            'Pemantauan status dan pendampingan respons administratif sesuai ruang lingkup.',
        ],
        'suitable_for' => 'Pelaku usaha, pemilik merek, kreator, atau desainer yang ingin mengajukan pelindungan merek, pencatatan hak cipta, maupun desain industri dan memahami risiko serta tahapan pemeriksaannya.',
        'workflow_steps' => [
            'Identifikasi objek, pemilik hak, dan jenis pelindungan KI yang paling relevan',
            'Penelusuran awal basis data dan pemeriksaan potensi persamaan atau kendala dasar',
            'Penentuan kelas barang atau jasa untuk merek, atau kategori objek untuk hak cipta dan desain industri',
            'Penyiapan identitas pemohon, label atau contoh karya, uraian, pernyataan, dan dokumen pendukung',
            'Pembuatan akun, pengajuan permohonan elektronik, dan pembayaran PNBP DJKI',
            'Pemantauan pemeriksaan formalitas, masa pengumuman, dan pemeriksaan substantif sesuai jenis KI',
            'Pendampingan pemenuhan kekurangan, tanggapan, atau dokumen pascapermohonan sesuai ruang lingkup',
            'Pengunduhan sertifikat atau surat pencatatan serta arahan pemeliharaan dan penggunaan hak',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi HAKI/Kekayaan Intelektual. Mohon dibantu menentukan jenis pelindungan, penelusuran awal, dokumen, dan alur permohonan DJKI.',
    ],
    [
        'icon' => 'desain',
        'slug' => 'desain-logo-label-kemasan',
        'title' => 'Desain Logo & Label Kemasan',
        'desc' => 'Perancangan logo dan label kemasan yang konsisten dengan identitas merek, karakter produk, target konsumen, serta kebutuhan produksi dan pemasaran.',
        'detail' => 'Layanan desain mencakup penggalian kebutuhan merek, pengumpulan materi produk, penyusunan arah visual, pengembangan konsep, revisi sesuai ruang lingkup yang disepakati, finalisasi artwork, dan penyerahan file. Untuk label kemasan, informasi legal dan isi wajib harus disediakan serta dikonfirmasi oleh pemilik produk; layanan desain tidak menggantikan penilaian BPOM, sertifikasi halal, pendaftaran merek, atau pemeriksaan hukum. Kesiapan cetak juga dikonfirmasi bersama spesifikasi percetakan atau kemasan yang digunakan.',
        'benefits' => [
            'Arah visual yang disusun dari karakter merek, produk, dan target konsumen.',
            'Hierarki informasi label yang lebih jelas dan mudah dibaca.',
            'Artwork disiapkan sesuai ukuran dan spesifikasi produksi yang disepakati.',
            'Penyerahan file final serta panduan penggunaan dasar sesuai ruang lingkup proyek.',
        ],
        'suitable_for' => 'Usaha baru yang membutuhkan identitas visual, merek yang melakukan penyegaran tampilan, dan pemilik produk yang memerlukan label kemasan untuk pemasaran atau persiapan produksi.',
        'workflow_steps' => [
            'Konsultasi brief mengenai merek, produk, target konsumen, media, dan tujuan desain',
            'Pengumpulan nama merek, naskah label, data produk, ukuran kemasan, dieline, dan referensi',
            'Audit visual sederhana serta penyusunan arah desain atau moodboard',
            'Pengembangan konsep awal sesuai ruang lingkup dan karakter merek yang disepakati',
            'Presentasi konsep, pemilihan arah, dan pengumpulan umpan balik terstruktur',
            'Revisi desain sesuai batas dan ruang lingkup pekerjaan yang disepakati',
            'Finalisasi artwork, tipografi, warna, tata letak, serta pemeriksaan teknis dasar',
            'Persetujuan akhir klien dan penyerahan file final untuk penggunaan digital atau produksi',
        ],
        'whatsapp_message' => 'Halo PT Zam Zam Khan, saya ingin konsultasi desain logo atau label kemasan. Mohon informasi kebutuhan brief, materi produk, spesifikasi ukuran, proses desain, dan file akhirnya.',
    ],
];
